boot.o: boot.S multiboot.h x86_desc.h types.h idt.h
idt_asm.o: idt_asm.S
page_asm.o: page_asm.S
x86_desc.o: x86_desc.S x86_desc.h types.h
i8259.o: i8259.c i8259.h lib.h types.h
idt.o: idt.c idt.h types.h x86_desc.h lib.h keyboard.h i8259.h rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h rtc.h page.h keyboard.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h
lib.o: lib.c lib.h types.h
page.o: page.c page.h types.h lib.h
rtc.o: rtc.c rtc.h types.h lib.h x86_desc.h i8259.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h
